services:
  pixo-rect:
    container_name: pixo-react
    restart: always
    image: node:22.12.0
    ports:
      - 3021:3000
    volumes:
      - ./:/usr/src/pixo
    working_dir: /usr/src/pixo

    networks:
      - app-network
    
    command: bash -c "yarn install && yarn run build && yarn run start"

networks:
  app-network:
    driver: bridge
    
